import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/Navbar'
import { DropdownNav } from '@/components/Dropdown'
import { Header } from '@/components/Header'
import { WeeklyDeals } from '@/components/Deals'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce app</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <DropdownNav />
      <Header />
      <main className='grid grid-cols-12 bg-primary-white py-12'>
        <div className='col-start-2 col-end-12 space-y-12'>
          <section className='weekly-deals-component bg-white'>
            <WeeklyDeals />
          </section>

          <section className='products-component bg-white'>
            <p className='p-2'>products</p>
          </section>
        </div>
      </main>
    </>
  )
}
